server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine2
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
turbine:
  aggregator:
    #cluster-config指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
    cluster-config: MICROSERVICE-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX2
    #配置Eureka中的serviceId列表，表明监控哪些服务
  app-config: microservice-consumer-movie-ribbon-with-hystrix2

#turbine默认监听的地址为服务的访问地址首页+hystrix.stream
#但是当微服务配置了管理接口，turbine默认监听的地址为服务的管理地址首页+hystrix.stream
#这个时候微服务配置的server.context-path不会影响这里，即不要配置turbine.instanceUrlSuffix

#instanceUrlSuffix默认为 hystrix.stream，由于需要监听的服务MICROSERVICE-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX2
#配置了server.context-path=/ribbon,所以有下面的配置

#turbine.instanceUrlSuffix.MICROSERVICE-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX2: ribbon/hystrix.stream

logging:
  level:
    root: INFO
    com.netflix.turbine.monitor: DEBUG