server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
turbine:
  aggregator:
    #cluster-config指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
    cluster-config: MICROSERVICE-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX
    #配置Eureka中的serviceId列表，表明监控哪些服务
  app-config: microservice-consumer-movie-ribbon-with-hystrix

logging:
  level:
    root: INFO
    com.netflix.turbine.monitor: DEBUG